#!/bin/sh
# This file is licensed under the public domain.

set -eu

TARGET="$1" # Example: riscv64-linux-gnu
MCPU="$2" # Examples: `baseline`, `native`, `generic+v7a`, or `arm1176jzf_s`

./build-host
./build-cross $1 $2
